/*
* Copyright (C) 2011-2019 ShenZhen iBOXCHAIN Information Technology Co.,Ltd.
* All right reserved.
*
* This software is the confidential and proprietary
* information of iBOXCHAIN Company of China.
* ("Confidential Information"). You shall not disclose
* such Confidential Information and shall use it only
* in accordance with the terms of the contract agreement
* you entered into with iBOXCHAIN inc.
*/

const CMD = [
  { name: '刷物品到包里', cmd: 'c_give(prefab,amount)' },
  { name: '刷物品到地上', cmd: 'c_spawn(prefab,amount)' },
  { name: '设置生命', cmd: 'c_sethealth(percent)' },
  { name: '设置饥饿', cmd: 'c_sethunger(percent)' },
  { name: '设置精神', cmd: 'c_setsanity(percent)' },
  { name: '设置湿度', cmd: ' c_setmoisture(percent)' },
  { name: '设置温度', cmd: 'c_settemperature(degrees)' },
  { name: '无敌（三维温度锁定）', cmd: 'c_godmode()' },
  { name: '超级无敌（三维回满，温度25）', cmd: 'c_supergodmode()' },
  { name: '加速（倍数）', cmd: 'c_speedmult(multiplier)' },
  { name: '创造模式（开关）', cmd: 'ThePlayer.components.builderGiveAllRecipes()' },
  { name: '修改最大生命值', cmd: 'ThePlayer.components.healthSetMax(value)' },
  { name: '修改最大饥饿值', cmd: 'ThePlayer.components.hungerSetMax(value)' },
  { name: '修改最大精神值', cmd: 'ThePlayer.components.sanitySetMax(value)' },
  { name: '停止饥饿', cmd: 'ThePlayer.components.hungerPause(true)' },
  { name: '设置攻击伤害倍数', cmd: 'ThePlayer.components.combat.damagemultiplier = value' },
  { name: '吴迪变身（1变回来）', cmd: 'ThePlayer.components.beavernessSetPercent(0/1)' },
  { name: '删除指针物品', cmd: 'c_select():Remove()' },
  { name: '跳过一个时期（白天变晚上）', cmd: 'TheWorldPushEvent(ms_nextphase)' },
  { name: '跳过一天', cmd: 'TheWorldPushEvent(ms_nextcycle)' },
  { name: '跳到某个季节', cmd: 'TheWorldPushEvent(ms_setseason, summer)' },
  { name: '下雨', cmd: 'TheWorldPushEvent(ms_forceprecipitation)' },
  { name: '停雨', cmd: 'TheWorldPushEvent(ms_forceprecipitation, false)' },
  { name: '指针处闪电', cmd: 'TheWorldPushEvent(ms_sendlightningstrike, ConsoleWorldPosition())' },
  { name: '指针处流星袭击', cmd: 'c_spawn(shadowmeteor, 1)' },
  { name: '重置全部世界', cmd: 'c_reset()' },
  { name: '回档，空参数回档一天', cmd: 'c_rollback(count)' }
]

const MATERIALS = [
  { name: '草', cmd: 'cutgrass' },
  { name: '树枝', cmd: 'twigs' },
  { name: '木头', cmd: 'log' },
  { name: '木炭', cmd: 'charcoal' },
  { name: '灰', cmd: 'ash' },
  { name: '采下的芦苇', cmd: 'cutreeds' },
  { name: '荧光果', cmd: 'lightbulb' },
  { name: '花瓣', cmd: 'petals' },
  { name: '噩梦花瓣', cmd: 'petals_evil' },
  { name: '松果', cmd: 'pinecone' },
  { name: '叶子', cmd: 'foliage' },
  { name: '摘下的苔藓', cmd: 'cutlichen' },
  { name: '虫子果', cmd: 'wormlight' },
  { name: '食人花种子', cmd: 'lureplantbulb' },
  { name: '燧石', cmd: 'flint' },
  { name: '硝石', cmd: 'nitre' },
  { name: '红宝石', cmd: 'redgem' },
  { name: '蓝宝石', cmd: 'bluegem' },
  { name: '紫宝石', cmd: 'purplegem' },
  { name: '绿宝石', cmd: 'greengem' },
  { name: '橙宝石', cmd: 'orangegem' },
  { name: '黄宝石', cmd: 'yellowgem' },
  { name: '岩石', cmd: 'rocks' },
  { name: '黄金', cmd: 'goldnugget' },
  { name: '铥矿石', cmd: 'thulecite' },
  { name: '铥矿碎片', cmd: 'thulecite_pieces' },
  { name: '绳子', cmd: 'rope' },
  { name: '木板', cmd: 'boards' },
  { name: '石砖', cmd: 'cutstone' },
  { name: '纸', cmd: 'papyrus' },
  { name: '犬牙', cmd: 'houndstooth' },
  { name: '猪皮', cmd: 'pigskin' },
  { name: '兔人尾巴', cmd: 'manrabbit_tail' },
  { name: '蜘蛛丝', cmd: 'silk' },
  { name: '蜘蛛腺体', cmd: 'spidergland' },
  { name: '蜘蛛卵', cmd: 'spidereggsack' },
  { name: '胡子', cmd: 'beardhair' },
  { name: '牛毛', cmd: 'beefalowool' },
  { name: '蜂巢', cmd: 'honeycomb' },
  { name: '蜂刺', cmd: 'stinger' },
  { name: '海象牙', cmd: 'walrus_tusk' },
  { name: '乌鸦羽毛', cmd: 'feather_crow' },
  { name: '红雀羽毛', cmd: 'feather_robin' },
  { name: '雪雀羽毛', cmd: 'feather_robin_winter' },
  { name: '牛角', cmd: 'horn' },
  { name: '触手皮', cmd: 'tentaclespots' },
  { name: '夏象鼻', cmd: 'trunk_summer' },
  { name: '冬象鼻', cmd: 'trunk_winter' },
  { name: '蜗牛龟粘液', cmd: 'slurtleslime' },
  { name: '蜗牛龟壳片', cmd: 'slurtle_shellpieces' },
  { name: '蝴蝶翅膀', cmd: 'butterflywings' },
  { name: '蚊子血囊', cmd: 'mosquitosack' },
  { name: '啜食者皮', cmd: 'slurper_pelt' },
  { name: '远古守护者角', cmd: 'minotaurhorn' },
  { name: '巨鹿眼球', cmd: 'deerclops_eyeball' },
  { name: '闪电羊角', cmd: 'lightninggoathorn' },
  { name: '格罗姆翅膀', cmd: 'glommerwings' },
  { name: '格罗姆花', cmd: 'glommerflower' },
  { name: '格罗姆粘液', cmd: 'glommerfuel' },
  { name: '活木头', cmd: 'livinglog' },
  { name: '噩梦燃料', cmd: 'nightmarefuel' },
  { name: '齿轮', cmd: 'gears' },
  { name: '晶体管', cmd: 'transistor' },
  { name: '大理石', cmd: 'marble' },
  { name: '硬骨头', cmd: 'boneshard' },
  { name: '冰', cmd: 'ice' },
  { name: '便便', cmd: 'poop' },
  { name: '鸟粪', cmd: 'guano' },
  { name: '蜻蜓鳞片', cmd: 'dragon_scales' },
  { name: '鹿鸭羽毛', cmd: 'goose_feather' },
  { name: '浣熊尾巴', cmd: 'coontail' },
  { name: '熊皮', cmd: 'bearger_fur' },
  { name: '砂石', cmd: 'townportaltalisman' },
  { name: '毒蟾蜍皮', cmd: 'shroom_skin' },
  { name: '无眼鹿茸', cmd: 'Deer_Antler' },
  { name: '克劳斯的鹿茸', cmd: 'KlausSackKey' },
  { name: '远古钥匙', cmd: 'atrium_key' },
  { name: '化石', cmd: 'fossil_piece' },
  { name: '暗影之心', cmd: 'shadowheart' }
]

const TOOL = [
  { name: '斧子', cmd: 'axe' },
  { name: '黄金斧头', cmd: 'goldenaxe' },
  { name: '露西斧子', cmd: 'lucy' },
  { name: '锤子', cmd: 'hammer' },
  { name: '镐', cmd: 'pickaxe' },
  { name: '黄金镐', cmd: 'goldenpickaxe' },
  { name: '铲子', cmd: 'shovel' },
  { name: '黄金铲子', cmd: 'goldenshovel' },
  { name: '草叉', cmd: 'pitchfork' },
  { name: '剃刀', cmd: 'razor' },
  { name: '捕虫网', cmd: 'bugnet' },
  { name: '鱼竿', cmd: 'fishingrod' },
  { name: '多功能工具', cmd: 'multitool_axe_pickaxe' },
  { name: '行走手杖', cmd: 'cane' },
  { name: '陷阱', cmd: 'trap' },
  { name: '鸟陷阱', cmd: 'birdtrap' },
  { name: '牙齿陷阱', cmd: 'trap_teeth' },
  { name: '麦斯威尔的牙齿陷阱', cmd: 'trap_teeth_maxwell' },
  { name: '背包', cmd: 'backpack' },
  { name: '猪皮包', cmd: 'piggyback' },
  { name: '坎普斯背包', cmd: 'krampus_sack' },
  { name: '雨伞', cmd: 'umbrella' },
  { name: '草伞', cmd: 'grass_umbrella' },
  { name: '保温石', cmd: 'heatrock' },
  { name: '草席卷', cmd: 'bedroll_straw' },
  { name: '毛皮铺盖', cmd: 'bedroll_furry' },
  { name: '火炬', cmd: 'torch' },
  { name: '提灯', cmd: 'lantern' },
  { name: '南瓜灯', cmd: 'pumpkin_lantern' },
  { name: '指南针', cmd: 'compass' },
  { name: '化肥', cmd: 'fertilizer' },
  { name: '灭火器', cmd: 'firesuppressor' },
  { name: '缝纫工具包', cmd: 'sewing_kit' }
]

const WEAPON = [
  { name: '矛', cmd: 'spear' },
  { name: '回旋镖', cmd: 'boomerang' },
  { name: '狼牙棒', cmd: 'tentaclespike' },
  { name: '吹箭', cmd: 'blowdart_pipe' },
  { name: '麻醉吹箭', cmd: 'blowdart_sleep' },
  { name: '燃烧吹箭', cmd: 'blowdart_fire' },
  { name: '火腿短棍', cmd: 'hambat' },
  { name: '暗影剑', cmd: 'nightsword' },
  { name: '蝙蝠棒', cmd: 'batbat' },
  { name: '远古短棒', cmd: 'ruins_bat' },
  { name: '瓦丝格雷斯矛', cmd: 'spear_wathgrithr' },
  { name: '排箫', cmd: 'panflute' },
  { name: '独奏乐器', cmd: 'onemanband' },
  { name: '火药', cmd: 'gunpowder' },
  { name: '蜜蜂地雷', cmd: 'beemine' },
  { name: '铃', cmd: 'bell' },
  { name: '红色护身符', cmd: 'amulet' },
  { name: '蓝色护身符', cmd: 'blueamulet' },
  { name: '紫色护身符', cmd: 'purpleamulet' },
  { name: '黄色护身符', cmd: 'yellowamulet' },
  { name: '橙色护身符', cmd: 'orangeamulet' },
  { name: '绿色护身符', cmd: 'greenamulet' },
  { name: '铥矿奖章', cmd: 'nightmare_timepiece' },
  { name: '冰魔杖', cmd: 'icestaff' },
  { name: '火魔杖', cmd: 'firestaff' },
  { name: '传送魔杖', cmd: 'telestaff' },
  { name: '橙色魔杖', cmd: 'orangestaff' },
  { name: '绿色魔杖', cmd: 'greenstaff' },
  { name: '黄色魔杖', cmd: 'yellowstaff' },
  { name: '探矿杖', cmd: 'diviningrod' },
  { name: '召唤鸟的书', cmd: 'book_birds' },
  { name: '召唤触手的书', cmd: 'book_tentacles' },
  { name: '催生植物的书', cmd: 'book_gardening' },
  { name: '催眠的书', cmd: 'book_sleep' },
  { name: '召唤闪电的书', cmd: 'book_brimstone' },
  { name: '麦斯威尔的日志', cmd: 'waxwelljournal' },
  { name: '阿比盖尔之花', cmd: 'abigail_flower' },
  { name: '空气球', cmd: 'balloons_empty' },
  { name: '气球', cmd: 'balloon' },
  { name: '薇洛的打火机', cmd: 'lighter' },
  { name: '切斯特骨眼', cmd: 'chester_eyebone' },
  { name: '羽毛扇', cmd: 'featherfan' },
  { name: '龙卷风魔杖', cmd: 'staff_tornado' },
  { name: '夜棍', cmd: 'nightstick' }
]

const WARE = [
  { name: '草帽', cmd: 'strawhat' },
  { name: '花环', cmd: 'flowerhat' },
  { name: '牛毛帽', cmd: 'beefalohat' },
  { name: '羽毛帽', cmd: 'featherhat' },
  { name: '猪皮帽', cmd: 'footballhat' },
  { name: '高礼帽', cmd: 'tophat' },
  { name: '兔耳罩', cmd: 'earmuffshat' },
  { name: '冬帽', cmd: 'winterhat' },
  { name: '矿工帽', cmd: 'minerhat' },
  { name: '蜘蛛帽', cmd: 'spiderhat' },
  { name: '蜂帽', cmd: 'beehat' },
  { name: '海象帽', cmd: 'walrushat' },
  { name: '蜗牛帽子', cmd: 'slurtlehat' },
  { name: '丛林帽', cmd: 'bushhat' },
  { name: '远古王冠', cmd: 'ruinshat' },
  { name: '防雨帽', cmd: 'rainhat' },
  { name: '冰帽', cmd: 'icehat' },
  { name: '西瓜帽', cmd: 'watermelonhat' },
  { name: '浣熊帽', cmd: 'catcoonhat' },
  { name: '瓦丝格雷斯帽', cmd: 'wathgrithrhat' },
  { name: '木盔甲', cmd: 'armorwood' },
  { name: '草盔甲', cmd: 'armorgrass' },
  { name: '大理石盔甲', cmd: 'armormarble' },
  { name: '夜魔盔甲', cmd: 'armor_sanity' },
  { name: '蜗牛龟盔甲', cmd: 'armorsnurtleshell' },
  { name: '远古盔甲', cmd: 'armorruins' },
  { name: '小巧背心', cmd: 'sweatervest' },
  { name: '夏日背心', cmd: 'trunkvest_summer' },
  { name: '寒冬背心', cmd: 'trunkvest_winter' },
  { name: '饥饿腰带', cmd: 'armorslurper' },
  { name: '雨衣', cmd: 'raincoat' },
  { name: '韦伯头骨', cmd: 'webberskull' },
  { name: '鼹鼠帽', cmd: 'molehat' },
  { name: '蜻蜓盔甲', cmd: 'armordragonfly' },
  { name: '熊背心', cmd: 'beargervest' },
  { name: '眼睛帽', cmd: 'eyebrellahat' },
  { name: '反射背心', cmd: 'reflectivevest' },
  { name: '夏威夷衬衫', cmd: 'hawaiianshirt' },
  { name: '时尚目镜', cmd: 'goggleshat' },
  { name: '沙漠护目镜', cmd: 'deserthat' },
  { name: '绿蘑菇帽', cmd: 'green_mushroomhat' },
  { name: '蓝蘑菇帽', cmd: 'blue_mushroomhat' },
  { name: '红蘑菇帽', cmd: 'red_mushroomhat' },
  { name: '暗影香炉', cmd: 'thurible' },
  { name: '骨甲', cmd: 'armorskeleton' }
]

const BUILDING = [
  { name: '营火', cmd: 'campfire' },
  { name: '石头营火', cmd: 'firepit' },
  { name: '冷火', cmd: 'coldfire' },
  { name: '石头冷火', cmd: 'coldfirepit' },
  { name: '锅', cmd: 'cookpot' },
  { name: '冰箱', cmd: 'icebox' },
  { name: '寒冰温度计', cmd: 'winterometer' },
  { name: '雨量计', cmd: 'rainometer' },
  { name: '一般农田', cmd: 'slow_farmplot' },
  { name: '高级农田', cmd: 'fast_farmplot' },
  { name: '午睡小屋', cmd: 'siestahut' },
  { name: '帐篷', cmd: 'tent' },
  { name: '路牌', cmd: 'homesign' },
  { name: '鸟笼', cmd: 'birdcage' },
  { name: '晾肉架', cmd: 'meatrack' },
  { name: '避雷针', cmd: 'lightning_rod' },
  { name: '盆栽', cmd: 'pottedfern' },
  { name: '暗夜照明灯', cmd: 'nightlight' },
  { name: '影灯', cmd: 'nightmarelight' },
  { name: '科学机器', cmd: 'researchlab' },
  { name: '炼金术引擎', cmd: 'researchlab2' },
  { name: '阴影操纵者', cmd: 'researchlab3' },
  { name: '灵子分解器', cmd: 'researchlab4' },
  { name: '木箱', cmd: 'treasurechest' },
  { name: '骷髅箱', cmd: 'skullchest' },
  { name: '华丽的箱子', cmd: 'pandoraschest' },
  { name: '大华丽的箱子', cmd: 'minotaurchest' },
  { name: '草墙', cmd: 'wall_hay_item' },
  { name: '木墙', cmd: 'wall_wood_item' },
  { name: '石墙', cmd: 'wall_stone_item' },
  { name: '铥墙', cmd: 'wall_ruins_item' },
  { name: '地上的草墙', cmd: 'wall_hay' },
  { name: '地上的木墙', cmd: 'wall_wood' },
  { name: '地上的石墙', cmd: 'wall_stone' },
  { name: '地上的铥墙', cmd: 'wall_ruins' },
  { name: '猪房', cmd: 'pighouse' },
  { name: '兔房', cmd: 'rabbithole' },
  { name: '鱼人房', cmd: 'mermhouse' },
  { name: '肉块雕像', cmd: 'resurrectionstatue' },
  { name: '重生石', cmd: 'resurrectionstone' },
  { name: '远古祭坛', cmd: 'ancient_altar' },
  { name: '损坏的远古祭坛', cmd: 'ancient_altar_broken' },
  { name: '传送核心', cmd: 'telebase' },
  { name: '宝石看台', cmd: 'gemsocket' },
  { name: '固定在地上的眼睛炮塔', cmd: 'eyeturret' },
  { name: '可带走的眼睛炮塔', cmd: 'eyeturret_item' },
  { name: '洞穴出口', cmd: 'cave_exit' },
  { name: '木地板', cmd: 'turf_woodfloor' },
  { name: '地毯地板', cmd: 'turf_carpetfloor' },
  { name: '棋盘地板', cmd: 'turf_checkerfloor' },
  { name: '冒险之门', cmd: 'adventure_portal' },
  { name: '火山坑', cmd: 'rock_light' },
  { name: '墓碑', cmd: 'gravestone' },
  { name: '坟墓土堆', cmd: 'mound' },
  { name: '人骨', cmd: 'skeleton' },
  { name: '狗骨头', cmd: 'houndbone' },
  { name: '动物足迹', cmd: 'animal_track' },
  { name: '可疑的土堆', cmd: 'dirtpile' },
  { name: '池塘', cmd: 'pond' },
  { name: '洞穴池塘', cmd: 'pond_cave' },
  { name: '猪头棍', cmd: 'pighead' },
  { name: '鱼头棍', cmd: 'mermhead' },
  { name: '猪火炬', cmd: 'pigtorch' },
  { name: '兔子洞', cmd: 'rabbithole' },
  { name: '蜂箱', cmd: 'beebox' },
  { name: '野生蜂窝', cmd: 'beehive' },
  { name: '杀人蜂窝', cmd: 'wasphive' },
  { name: '洞穴蜘蛛洞', cmd: 'spiderhole' },
  { name: '海象窝', cmd: 'walrus_camp' },
  { name: '高鸟窝', cmd: 'tallbirdnest' },
  { name: '猎犬丘', cmd: 'houndmound' },
  { name: '蜗牛窝', cmd: 'slurtlehole' },
  { name: '蝙蝠洞', cmd: 'batcave' },
  { name: '猴子桶', cmd: 'monkeybarrel' },
  { name: '蜘蛛巢穴', cmd: 'spiderden' },
  { name: '鼹鼠丘', cmd: 'molehill' },
  { name: '浣熊洞', cmd: 'catcoonden' },
  { name: '带硝石的岩石', cmd: 'rock1' },
  { name: '带黄金的岩石', cmd: 'rock2' },
  { name: '只有石头的岩石', cmd: 'rock_flintless' },
  { name: '大圆洞穴石头', cmd: 'stalagmite_full' },
  { name: '中圆洞穴石头', cmd: 'stalagmite_med' },
  { name: '小圆洞穴石头', cmd: 'stalagmite_low' },
  { name: '大高洞穴石头', cmd: 'stalagmite_tall_full' },
  { name: '中高洞穴石头', cmd: 'stalagmite_tall_med' },
  { name: '小高洞穴石头', cmd: 'stalagmite_tall_low' },
  { name: '冰石', cmd: 'rock_ice' },
  { name: '远古头像', cmd: 'ruins_statue_head' },
  { name: '远古法师雕像', cmd: 'ruins_statue_mage' },
  { name: '大理石柱子', cmd: 'marblepillar' },
  { name: '大理石树', cmd: 'marbletree' },
  { name: '竖琴雕像', cmd: 'statueharp' },
  { name: '玄武岩', cmd: 'basalt' },
  { name: '高玄武岩', cmd: 'basalt_pillar' },
  { name: '猪王矮柱石', cmd: 'insanityrock' },
  { name: '猪王高柱石', cmd: 'sanityrock' },
  { name: '远古椅子', cmd: 'ruins_chair' },
  { name: '远古花瓶', cmd: 'ruins_vase' },
  { name: '远古桌子', cmd: 'ruins_table' },
  { name: '麦斯威尔雕像', cmd: 'statuemaxwell' },
  { name: '格罗门雕像', cmd: 'statueglommer' },
  { name: '废墟', cmd: 'relic' },
  { name: '损毁的废墟', cmd: 'ruins_rubble' },
  { name: '损坏的雕像', cmd: 'bishop_nightmare' },
  { name: '损坏的战车', cmd: 'rook_nightmare' },
  { name: '损坏的骑士', cmd: 'knight_nightmare' },
  { name: '损坏的机械1', cmd: 'chessjunk1' },
  { name: '损坏的机械2', cmd: 'chessjunk2' },
  { name: '损坏的机械3', cmd: 'chessjunk3' },
  { name: '环状传送机零件', cmd: 'teleportato_ring' },
  { name: '盒状传送机零件', cmd: 'teleportato_box' },
  { name: '曲柄状传送机零件', cmd: 'teleportato_crank' },
  { name: '球状传送机零件', cmd: 'teleportato_potato' },
  { name: '传送机零件底座', cmd: 'teleportato_base' },
  { name: '传送机零件底座', cmd: 'teleportato_checkmate' },
  { name: '虫洞', cmd: 'wormhole' },
  { name: '被限制的虫洞', cmd: 'wormhole_limited_1' },
  { name: '小星星', cmd: 'stafflight' },
  { name: '箱子陷阱', cmd: 'treasurechest_trap' },
  { name: '冰包', cmd: 'icepack' },
  { name: '蜻蜓箱子', cmd: 'dragonflychest' },
  { name: '地陷', cmd: 'antlion_sinkhole' },
  { name: '落石', cmd: 'cavein_boulder' },
  { name: '慵懒的传送者', cmd: 'townportal' },
  { name: '多肉植物盆栽', cmd: 'succulent_potted' },
  { name: '玻璃尖锥 小', cmd: 'glassspike_short' },
  { name: '玻璃尖锥 中', cmd: 'glassspike_med' },
  { name: '玻璃尖锥 大', cmd: 'glassspike_tall' },
  { name: '玻璃陈堡', cmd: 'glassblock' },
  { name: '蘑菇灯 单', cmd: 'mushroom_light' },
  { name: '蘑菇灯 多重', cmd: 'mushroom_light2' },
  { name: '克劳斯的袋子', cmd: 'Klaus_sack' }
]

const FOOD = [
  { name: '胡萝卜', cmd: 'carrot' },
  { name: '熟胡萝卜', cmd: 'carrot_cooked' },
  { name: '浆果', cmd: 'berries' },
  { name: '熟浆果', cmd: 'berries_cooked' },
  { name: '南瓜', cmd: 'pumpkin' },
  { name: '熟南瓜', cmd: 'pumpkin_cooked' },
  { name: '火龙果', cmd: 'dragonfruit' },
  { name: '熟火龙果', cmd: 'dragonfruit_cooked' },
  { name: '石榴', cmd: 'pomegranate' },
  { name: '熟石榴', cmd: 'pomegranate_cooked' },
  { name: '玉米', cmd: 'corn' },
  { name: '熟玉米', cmd: 'corn_cooked' },
  { name: '榴莲', cmd: 'durian' },
  { name: '熟榴莲', cmd: 'durian_cooked' },
  { name: '茄子', cmd: 'eggplant' },
  { name: '熟茄子', cmd: 'eggplant_cooked' },
  { name: '洞穴香蕉', cmd: 'cave_banana' },
  { name: '熟洞穴香蕉', cmd: 'cave_banana_cooked' },
  { name: '橡果', cmd: 'acorn' },
  { name: '熟橡果', cmd: 'acorn_cooked' },
  { name: '仙人掌肉', cmd: 'cactus_meat' },
  { name: '西瓜', cmd: 'watermelon' },
  { name: '采摘的红蘑菇', cmd: 'red_cap' },
  { name: '煮熟的红蘑菇', cmd: 'red_cap_cooked' },
  { name: '采摘的绿蘑菇', cmd: 'green_cap' },
  { name: '煮熟的绿蘑菇', cmd: 'green_cap_cooked' },
  { name: '煮熟的蓝蘑菇', cmd: 'blue_cap_cooked' },
  { name: '采摘的蓝蘑菇', cmd: 'blue_cap' },
  { name: '种子', cmd: 'seeds' },
  { name: '熟种子', cmd: 'seeds_cooked' },
  { name: '胡萝卜种子', cmd: 'carrot_seeds' },
  { name: '南瓜种子', cmd: 'pumpkin_seeds' },
  { name: '火龙果种子', cmd: 'dragonfruit_seeds' },
  { name: '石榴种子', cmd: 'pomegranate_seeds' },
  { name: '玉米种子', cmd: 'corn_seeds' },
  { name: '榴莲种子', cmd: 'durian_seeds' },
  { name: '茄子种子', cmd: 'eggplant_seeds' },
  { name: '小肉', cmd: 'smallmeat' },
  { name: '小熟肉', cmd: 'cookedsmallmeat' },
  { name: '小干肉', cmd: 'smallmeat_dried' },
  { name: '大肉', cmd: 'meat' },
  { name: '大熟肉', cmd: 'cookedmeat' },
  { name: '大干肉', cmd: 'meat_dried' },
  { name: '鸡腿', cmd: 'drumstick' },
  { name: '熟鸡腿', cmd: 'drumstick_cooked' },
  { name: '疯肉', cmd: 'monstermeat' },
  { name: '熟疯肉', cmd: 'cookedmonstermeat' },
  { name: '干疯肉', cmd: 'monstermeat_dried' },
  { name: '食人花肉', cmd: 'plantmeat' },
  { name: '熟食人花肉', cmd: 'plantmeat_cooked' },
  { name: '鸡蛋', cmd: 'bird_egg' },
  { name: '煮熟的鸡蛋', cmd: 'bird_egg_cooked' },
  { name: '烂鸡蛋', cmd: 'rottenegg' },
  { name: '高鸟蛋', cmd: 'tallbirdegg' },
  { name: '熟高鸟蛋', cmd: 'tallbirdegg_cooked' },
  { name: '孵化的高鸟蛋', cmd: 'tallbirdegg_cracked' },
  { name: '鱼', cmd: 'fish' },
  { name: '熟鱼', cmd: 'fish_cooked' },
  { name: '鳗鱼', cmd: 'eel' },
  { name: '熟鳗鱼', cmd: 'eel_cooked' },
  { name: '蛙腿', cmd: 'froglegs' },
  { name: '熟蛙腿', cmd: 'froglegs_cooked' },
  { name: '蝙蝠翅膀', cmd: 'batwing' },
  { name: '熟蝙蝠翅膀', cmd: 'batwing_cooked' },
  { name: '曼德拉草', cmd: 'mandrake' },
  { name: '熟曼特拉草', cmd: 'cookedmandrake' },
  { name: '蜂蜜', cmd: 'honey' },
  { name: '黄油', cmd: 'butter' },
  { name: '奶油松饼', cmd: 'butterflymuffin' },
  { name: '青蛙圆面包三明治', cmd: 'frogglebunwich' },
  { name: '蜜汁火腿', cmd: 'honeyham' },
  { name: '龙馅饼', cmd: 'dragonpie' },
  { name: '太妃糖', cmd: 'taffy' },
  { name: '南瓜饼', cmd: 'pumpkincookie' },
  { name: '肉串', cmd: 'kabobs' },
  { name: '芝士蛋糕', cmd: 'powcake' },
  { name: '曼德拉草汤', cmd: 'mandrakesoup' },
  { name: '鸡蛋火腿', cmd: 'baconeggs' },
  { name: '肉汤', cmd: 'bonestew' },
  { name: '半圆小酥饼', cmd: 'perogies' },
  { name: '湿腻焦糊', cmd: 'wetgoop' },
  { name: '蹩脚的炖菜', cmd: 'ratatouille' },
  { name: '水果拼盘', cmd: 'fruitmedley' },
  { name: '玉米饼包炸鱼', cmd: 'fishtacos' },
  { name: '华夫饼', cmd: 'waffles' },
  { name: '火鸡正餐', cmd: 'turkeydinner' },
  { name: '鱼肉条', cmd: 'fishsticks' },
  { name: '香酥茄盒', cmd: 'stuffedeggplant' },
  { name: '甜蜜金砖', cmd: 'honeynuggets' },
  { name: '肉丸', cmd: 'meatballs' },
  { name: '果酱蜜饯', cmd: 'jammypreserves' },
  { name: '怪物千层饼', cmd: 'monsterlasagna' },
  { name: '鳗鱼料理', cmd: 'unagi' },
  { name: '蜂蜜绷带', cmd: 'bandage' },
  { name: '治疗药膏', cmd: 'healingsalve' },
  { name: '腐烂食物', cmd: 'spoiled_food' },
  { name: '花沙拉', cmd: 'flowersalad' },
  { name: '冰激淋', cmd: 'icecream' },
  { name: '西瓜冰', cmd: 'watermelonicle' },
  { name: '干果', cmd: 'trailmix' },
  { name: '咖喱', cmd: 'hotchili' },
  { name: '鳄梨酱', cmd: 'guacamole' },
  { name: '羊奶', cmd: 'goatmilk' }
]

const PLANT = [
  { name: '花', cmd: 'flower' },
  { name: '噩梦花', cmd: 'flower_evil' },
  { name: '长在地上的胡萝卜', cmd: 'carrot_planted' },
  { name: '长在地上的草', cmd: 'grass' },
  { name: '草根', cmd: 'depleted_grass' },
  { name: '长草簇', cmd: 'dug_grass' },
  { name: '树苗', cmd: 'sapling' },
  { name: '可种的树苗', cmd: 'dug_sapling' },
  { name: '果树丛', cmd: 'berrybush' },
  { name: '可种的果树丛', cmd: 'dug_berrybush' },
  { name: '果树丛2', cmd: 'berrybush2' },
  { name: '可种的果树丛2', cmd: 'dug_berrybush2' },
  { name: '尖刺灌木', cmd: 'marsh_bush' },
  { name: '可种的尖刺灌木', cmd: 'dug_marsh_bush' },
  { name: '芦苇', cmd: 'reeds' },
  { name: '洞穴苔藓', cmd: 'lichen' },
  { name: '蕨类植物', cmd: 'cave_fern' },
  { name: '树', cmd: 'evergreen' },
  { name: '无松果的树', cmd: 'evergreen_sparse' },
  { name: '针叶树', cmd: 'marsh_tree' },
  { name: '洞穴香蕉树', cmd: 'cave_banana_tree' },
  { name: '活树', cmd: 'livingtree' },
  { name: '橡树', cmd: 'deciduoustree' },
  { name: '高橡树', cmd: 'deciduoustree_tall' },
  { name: '矮橡树', cmd: 'deciduoustree_short' },
  { name: '红蘑菇', cmd: 'red_mushroom' },
  { name: '绿蘑菇', cmd: 'green_mushroom' },
  { name: '蓝蘑菇', cmd: 'blue_mushroom' },
  { name: '高蘑菇树', cmd: 'mushtree_tall' },
  { name: '中蘑菇树', cmd: 'mushtree_medium' },
  { name: '小蘑菇树', cmd: 'mushtree_small' },
  { name: '单朵洞穴花', cmd: 'flower_cave' },
  { name: '双朵洞穴花', cmd: 'flower_cave_double' },
  { name: '三朵洞穴花', cmd: 'flower_cave_triple' },
  { name: '滚草', cmd: 'tumbleweed' },
  { name: '仙人掌', cmd: 'cactus' },
  { name: '仙人掌花', cmd: 'cactus_flower' },
  { name: '水塘边小草', cmd: 'marsh_plant' },
  { name: '水藻', cmd: 'pond_algae' },
  { name: '毒蘑菇树', cmd: 'mushroomsprout' }
]

const ANIMAL = [
  { name: '兔子', cmd: 'rabbit' },
  { name: '火鸡', cmd: 'perd' },
  { name: '乌鸦', cmd: 'crow' },
  { name: '红雀', cmd: 'robin' },
  { name: '雪雀', cmd: 'robin_winter' },
  { name: '蝴蝶', cmd: 'butterfly' },
  { name: '萤火虫', cmd: 'fireflies' },
  { name: '蜜蜂', cmd: 'bee' },
  { name: '杀人蜂', cmd: 'killerbee' },
  { name: '苍蝇', cmd: 'flies' },
  { name: '蚊子', cmd: 'mosquito' },
  { name: '青蛙', cmd: 'frog' },
  { name: '牛', cmd: 'beefalo' },
  { name: '小牛', cmd: 'babybeefalo' },
  { name: '闪电羊', cmd: 'lightninggoat' },
  { name: '猪人', cmd: 'pigman' },
  { name: '猪守卫', cmd: 'pigguard' },
  { name: '兔人', cmd: 'bunnyman' },
  { name: '鱼人', cmd: 'merm' },
  { name: '洞穴蜘蛛', cmd: 'spider_hider' },
  { name: '喷射蜘蛛', cmd: 'spider_spitter' },
  { name: '地面小蜘蛛', cmd: 'spider' },
  { name: '地面绿蜘蛛', cmd: 'spider_warrior' },
  { name: '蜘蛛女王', cmd: 'spiderqueen' },
  { name: '白蜘蛛', cmd: 'spider_dropper' },
  { name: '猎狗', cmd: 'hound' },
  { name: '红色猎狗', cmd: 'firehound' },
  { name: '冰狗', cmd: 'icehound' },
  { name: '触手', cmd: 'tentacle' },
  { name: '巨型触手', cmd: 'tentacle_garden' },
  { name: '树精', cmd: 'leif' },
  { name: '稀有树精', cmd: 'leif_sparse' },
  { name: '海象', cmd: 'walrus' },
  { name: '小海象', cmd: 'little_walrus' },
  { name: '小高鸟', cmd: 'smallbird' },
  { name: '青年高鸟', cmd: 'teenbird' },
  { name: '高鸟', cmd: 'tallbird' },
  { name: '夏象', cmd: 'koalefant_summer' },
  { name: '冬象', cmd: 'koalefant_winter' },
  { name: '企鹅', cmd: 'penguin' },
  { name: '蜗牛龟', cmd: 'slurtle' },
  { name: '黏糊虫', cmd: 'snurtle' },
  { name: '蝙蝠', cmd: 'bat' },
  { name: '龙虾', cmd: 'rocky' },
  { name: '猴子', cmd: 'monkey' },
  { name: '缀食者', cmd: 'slurper' },
  { name: '秃鹫', cmd: 'buzzard' },
  { name: '鼹鼠', cmd: 'mole' },
  { name: '浣熊', cmd: 'catcoon' },
  { name: '发条骑士', cmd: 'knight' },
  { name: '主教', cmd: 'bishop' },
  { name: '战车', cmd: 'rook' },
  { name: '爬行暗影怪', cmd: 'crawlinghorror' },
  { name: '尖嘴暗影怪', cmd: 'terrorbeak' },
  { name: '巨鹿', cmd: 'deerclops' },
  { name: '远古守护者', cmd: 'minotaur' },
  { name: '远古虫子1', cmd: 'stalker_minion1' },
  { name: '远古虫子2', cmd: 'stalker_minion2' },
  { name: '远古虫子', cmd: 'worm' },
  { name: '阿比盖尔', cmd: 'abigail' },
  { name: '幽灵', cmd: 'ghost' },
  { name: '麦斯威尔黑影小人', cmd: 'shadowwaxwell' },
  { name: '坎普斯', cmd: 'krampus' },
  { name: '格罗门', cmd: 'glommer' },
  { name: '切斯特', cmd: 'chester' },
  { name: '食人花', cmd: 'lureplant' },
  { name: '食人花眼睛', cmd: 'eyeplant' },
  { name: '大脚', cmd: 'bigfoot' },
  { name: '猪王', cmd: 'pigking' },
  { name: '鹿鸭', cmd: 'moose' },
  { name: '小鸭', cmd: 'mossling' },
  { name: '蜻蜓', cmd: 'dragonfly' },
  { name: '座狼', cmd: 'warg' },
  { name: '熊', cmd: 'bearger' },
  { name: '坚果鸭', cmd: 'birchnutdrake' },
  { name: '鹿鸭蛋', cmd: 'mooseegg' },
  { name: '蚁狮', cmd: 'antlion' },
  { name: '蛤蟆', cmd: 'toadstool' },
  { name: '克劳斯', cmd: 'klaus' },
  { name: '森林狩猎者', cmd: 'stalker_forest' },
  { name: '暗影狩猎者', cmd: 'stalker' },
  { name: '远古狩猎者', cmd: 'stalker_atrium' }
]

const TAB_LIST = [
  { title: '操作命令' },
  { title: '材料' },
  { title: '工具' },
  { title: '武器' },
  { title: '穿戴' },
  { title: '建筑' },
  { title: '食物' },
  { title: '植物' },
  { title: '动物' }
]

export {
  TAB_LIST,
  CMD,
  MATERIALS,
  TOOL,
  WEAPON,
  WARE,
  BUILDING,
  FOOD,
  PLANT,
  ANIMAL
}
